# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d95fc3f2328a5a9583aa0776161e7174520d0f275e07132d9e60bc993a70ee216f7417167ca1f055eff89dd18e2cc0025ede38575ab2ad5370afe41a68525974
  database_username: PT_TO_H
  database_password: PT_TO_H

test:
  secret_key_base: 7460231408c5b001d1ab3e611cff289360f5f013fbb5534037f04af1f88474ff450bd2a3ee78ecb23fb59df1d09f037a09dadf2ddb7acbbfe599dace289e95db
  database_username: PT_TO_H
  database_password: PT_TO_H

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  database_username: <%= ENV['PIVOTALTRACKERTOHARVEST_DATABASE_USERNAME'] %>
  database_password: <%= ENV['PIVOTALTRACKERTOHARVEST_DATABASE_PASSWORD'] %>

# Since I use Nginx and Passenger, I set these environment vars in 
# passenger_env_var SECRET_KEY_BASE 24766a02211065ff216dc5cce30a4e3991b2eb5dbacd11ad54fa72a86885e2f3dab1c7a203e41c22ee38458af1f9eda2a4b851648dc634e5f0ce7efdc0bdfcec;
# passenger_env_var PIVOTALTRACKERTOHARVEST_DATABASE_USERNAME PT_TO_H;
# passenger_env_var PIVOTALTRACKERTOHARVEST_DATABASE_PASSWORD PT_TO_H;


